### ISSUE TITLE
Better BibTeX disabled after automatic Zotero update

### ISSUE THREAD

**Issue by MiltAmsterdam** [ZotPlus/zotero-better-bibtex#225] opened 2015-07-01 12:45 UTC
Hi, 

I got the error that Better BibTeX disabled because it found Zotero 4.0.27.SOURCE, but requires 4.0.27 or later.... 
![zotero-error](https://cloud.githubusercontent.com/assets/13135233/8454693/c57516c6-1fff-11e5-8172-89edd4ffbcf8.png)

Any solutions?

Thanks!

Emily

**Comment by cpence** [comment] 2015-07-01 13:01
I also just hit an automatic update and BBT says "has been disabled because it did not find 4.0.27 or later." Went and re-downloaded a fresh copy of 4.0.27 (Mac) from the Zotero website, still getting the same error.

**Comment by cpence** [comment] 2015-07-01 13:02
Hah, awesome, nevermind. =D

**Comment by retorquere** [comment] 2015-07-01 13:04
The solution is for me to test better :( sorry guys. .15 will be out in a few minutes. The "source" warning stays, Zotero should report "4.0.27" for standalone, not "4.0.27.SOURCE", it presents itself as a debug version, which threw me off. I've reported it to the Zotero guys, the message I present is harmless, and they'll probably update standalone soon.

**Comment by retorquere** [comment] 2015-07-01 13:08
Get yours now at a repo near you.

**Comment by MiltAmsterdam** [comment] 2015-07-01 13:12
Awesome! Thanks for the quick fix and making my day! :D 
(so to get rid of the error  message we'll have to wait for Zotero's update, right?)

**Comment by retorquere** [comment] 2015-07-01 13:15
If it makes your day it has made mine; thank you! Yes, the warning will disappear once Zotero Standalone updates; the dev are usually super-responsive so it shouldn't take long.

**Comment by retorquere** [comment] 2015-07-01 13:21
(BTW, I prefer for users to close the issue, indicating the problem is indeed solved for them, rather than me assuming it on their behalf. Take your time, but I'd appreciate it if you could close the issue after you've confirmed it works for you)

**Closed** 2015-07-01 13:35 UTC
