### ISSUE TITLE
Copyright sign in bibliography trips up MikTeX

### ISSUE THREAD

**Issue by readerneu** [ZotPlus/zotero-better-bibtex#374] opened 2015-10-13 21:12 UTC
Hello,

I have used a combination of zotero with better biblatex and the zotero autoexport to set up the .bib-file for my latex document.
Since July (I assume due to a Firefox update) this solution doesn't work anymore and I don't know why.

1. Zotero autoexport says it exported the bibliography but in fact it didn't (complains of wrong path even though I haven't changed anything.

2. I tried to set up my .bib-file by using the export function of zotero. I need to use better biblatex to generate the correct citekey. But instead of

@article{Ehlis2005MultiE.H.W.F+,
title = {Multi-channel near-infrared spectroscopy detects specific inferior-frontal activation during incongruent Stroop trials},
volume = {69},
url = {http://www.sciencedirect.com/science/article/pii/S0301051104001619},
doi = {10.1016/j.biopsycho.2004.09.003},
timestamp = {2014-08-23 09:41:11},
number = {3},
urldate = {2014-08-23},
journal = {Biological Psychology},
author = {Ehlis, A. -C. and Herrmann, M. J. and Wagener, A. and Fallgatter, A. J.},
month = jul,
year = {2005},
keywords = {Cognitive interference,Near-infrared spectroscopy,NIRS,Optical topography,Stroop task},
pages = {315--331}
}

the same citation is now exported as

@article{Ehlis2005MultiE.H.W.F+,
title = {Multi-channel near-infrared spectroscopy detects specific inferior-frontal activation during incongruent {Stroop} trials},
volume = {69},
url = {http://www.sciencedirect.com/science/article/pii/S0301051104001619},
doi = {10.1016/j.biopsycho.2004.09.003},
timestamp = {2014-08-23T09:41:11Z},
number = {3},
journaltitle = {Biological {Psychology}},
shortjournal = {Biological {Psychology}},
author = {Ehlis, {A}. -{C}. and {Herrmann}, {M}. {J}. and {Wagener}, {A}. and {Fallgatter}, {A}. {J}.},
urldate = {2014-08-23},
date = {2005-07},
pages = {315--331},
keywords = {Cognitive interference,Near-infrared spectroscopy,NIRS,Optical topography,Stroop task}
}

So Latex is complaining about
! LaTeX Error: Command \texteuro unavailable in encoding T1.

It seems like this problem is known for Lyx but should be solved by using biblatex which I do.

Here you can find my complete .bib files (old one and the zotero-biblatex export)

https://www.dropbox.com/sh/zq5g7boba6rq9ah/AADcDvgv7L6pBc0bZ-IrpRFYa?dl=0

I'm very grateful for every hint!

**Comment by retorquere** [comment] 2015-10-13 22:20
1. I don't know why ZAE doesn't work; you'll have to ask the author. BBT does include its own auto-exporter, you could try to use that.

2. The extra braces are due to a defaults change; you can change it back by setting the BBT pref "preserve capitals" to "inner"

3. `\texteuro` doesn't appear in the Better BibLaTeX export Bibliography_better_biblatexexport.bib or Bibliography_zotero_biblatexexport.bib but it does occur in Bibliography_old.bib. Are you using Bibliography_better_biblatexexport.bib?

**Comment by karnesky** [comment] 2015-10-13 22:48
@readerneu posted his bibliography to:
https://www.dropbox.com/sh/zq5g7boba6rq9ah/AADcDvgv7L6pBc0bZ-IrpRFYa?dl=0

It seems that the reference for 'Baseline' is corrupt.  I won't speculate on why or what the full info for that reference is.

**Comment by retorquere** [comment] 2015-10-13 22:59
There's 3 files there, but as noted, only one includes `\texteuro`. That's not necessarily corrupt, but you need to do some setup to have the bib processor recognise it correctly. But I would venture to guess that during reference import from science direct, some charset snafu occurred.

@readerneu, can you right-click that reference ("Baseline ‘state anxiety’ influences HPA-axis sensitivity to one sham-controlled HF-rTMS session applied to the right dorsolateral prefrontal cortex"), select "report zotplus error", and post the debug ID here? That should allow me to assess whether it's an export error, or whether the exporter is correctly exporting incorrect input.

**Comment by readerneu** [comment] 2015-10-14 15:59
I updated the dropbox folder. I changed the "preserve capitals" to "inner". Latex complains about the same problem.

Debug ID is: KWSZPH4Q

**Comment by retorquere** [comment] 2015-10-14 16:13
Bibliography_betterbiblatex_capitals_inner.bib in that folder still does not contain `\texteuro`, only Bibliography_old.bib does (the setting to "inner" affected only the extra braces in the output you showed above). Are you *sure* you are compiling only using Bibliography_betterbiblatex_capitals_inner.bib? Because if so, that bibliography is not the cause of the error. If you are compiling against Bibliography_old.bib, that explains the error, but not how it goth there, as the source reference you submitted exports cleanly for me.

**Comment by readerneu** [comment] 2015-10-14 16:34
Well the funny thing is with bibliography_old.bib I don't get those errors. When I compile with Bibliography_betterbiblatex_capitals_inner.bib I get them. So I think the new bibliography has to cause the error. If it makes it easier for you I can send you the latex document too?

**Comment by readerneu** [comment] 2015-10-14 16:36
And Yes I am sure that I'm compiling with Bibliography_betterbiblatex_capitals_inner.bib.

**Comment by readerneu** [comment] 2015-10-14 16:39
Another thing I was surprised about is earlier the date was exported as 
month = jul,
year = {2005},

now it is exported as

date = {2005-07},

**Comment by retorquere** [comment] 2015-10-14 16:41
The reason why I am asking is this:

```
$ grep -c texteuro ~/Downloads/Bibliography_betterbiblatex_capitals_inner.bib 
0
```

**Comment by retorquere** [comment] 2015-10-14 16:43
WRT the 2005-07 date: that might be because BBT has a better date parser now. To assess whether 2005-7 is correct or not I'd need to have the source reference; you can send it as a debug ID if you want me to inspect.

You can drop your LaTeX file into https://dbinbox.com/retorquere

**Comment by retorquere** [comment] 2015-10-14 16:51
and
```
$ grep -c texteuro ~/Downloads/Bibliography_old.bib 
1
```
so if the error is directly caused by the presence of `\texteuro` rather the report about `\texteuro` being collateral damage from an earlier error, I don't see how Bibliography_betterbiblatex_capitals_inner.bib could be causing it, as that command is not in there. Your LaTeX file might tell me more.

**Comment by readerneu** [comment] 2015-10-14 17:08
I assume that 2005-07 is causing problems because the bibliography I customized in my latex document assumes the month, year format

**Comment by readerneu** [comment] 2015-10-14 17:09
*it expects month, year format

**Comment by readerneu** [comment] 2015-10-14 17:13
the backup version is a simplified one which still produces the same error. The bib. file is the same but has another name...

**Comment by retorquere** [comment] 2015-10-14 17:37
When I compile Dissertation_backup.tex, I only get the expected "Empty bibliography on input line 148.". 

When I compile Dissertation.tex, I first got "LaTeX Error: File `includes/06Anhang.tex' not found."; commenting out that line, I get "Empty bibliography on input line 331."

Both of these was with file:///home/emile/Downloads/Bibliography_betterbiblatex_capitals_inner.bib

I've put them up at https://www.sharelatex.com/project/54feca38f58d781e0c982eeb, can you get it back to the point where it fails?

Can you submit a separate issue for the date formatting? I'm not yet sure how I'm going to handle it, but it's a different problem from the `\texteuro` issue you're running into.

**Comment by readerneu** [comment] 2015-10-14 18:09
Sure I'll do. 

I tried to update the sharelatex project but I don't know how to insert the bibliography. So I sent you all the files you need in a .rar file. You just have to adjust the .bib path in the .tex file. Thanks a lot for your effort!

**Comment by retorquere** [comment] 2015-10-14 18:35
What command do you use to compile this? I've updated sharelatex but it gives 200+ errors when I try to compile.

I don't want to edit the files since they're in a charset I'm not sure gets safely through my editor. Could you move everything in a single directory, and remove all the directory names from the paths in the .tex files (so `includes/` and `F:/Dropbox/Literaturverzeichnis/Latex Folder/`) and send them again?

**Comment by retorquere** [comment] 2015-10-14 19:17
I can reproduce the error; The culprit was in fact (a.o.) `Wendt2008BrainW.L.W.H.H+`, which has an euro-sign in the copyright field. Your Bibliography_old did not have any of these. From what I can tell, these are added after Bibliography_old was generated, and BBT exports these correctly.

The quick way out of this is to add `rights` to your `skipfields`, but it's a stop-gap measure. You could also try to set BBT to export to ascii; it will change the euro symbol into `\texteuro`; your Bibliography_old had those (but I don't know if you actually referenced it; if not, it would not have made it into the token stream I think), and it didn't seem to mind them.

To really address the error requires fiddling with font files and such; tex.stackexchange.com will be a better source of help than I.

BTW, your tex sources are encoded in ISO-8859; the bibliography generated by BBT is always in UTF-8. I don't know how well the LaTeX compilers deal with mixed encodings.

**Comment by retorquere** [comment] 2015-10-14 19:19
(edit: not a euro-sign but a copyright sign. The error messages from LaTeX are not always very enlightening. Or helpful. Or accurate)

**Comment by retorquere** [comment] 2015-10-14 19:21
Hold on, there's more going on.

**Comment by retorquere** [comment] 2015-10-14 19:28
It's a general unicode problem; just excluding "rights" won't do it. The 2nd reference has `year = {März 1, 2008}`, which also trips up compilation. Which LaTeX compiler are you using?

There is a separate problem in that `März 1, 2008` is not being parsed properly and is being treated as a literal date. I'm looking into that.

**Comment by readerneu** [comment] 2015-10-14 19:40
I use texmaker with miktex

**Comment by retorquere** [comment] 2015-10-14 22:09
There is a problem in the upstream date parser I use; I'm trying to resolve it with the author.

**Comment by retorquere** [comment] 2015-10-15 08:10
OK, the date problem has a workaround; the tests pass, so 1.5.10 will be released momentarily.

To get back to the problems you are facing:

1. Please open a new issue for preferred date formatting. I hadn't thought about date-ish things in date fields that one would not want to have parsed and reformatted but to be retained as-is.
2. The output seems to be correct given the probably input. Try the skipFields option as in on 1.5.10, or try setting the ascii option, as a workaround.
3. I would still recommend finding a structural solution on tex.stackexchange.com given the fact that the bib file (if processed with BibLaTeX) seems to be valid.

**Comment by retorquere** [comment] 2015-10-17 10:02
Is there still anything I can do for you?

**Comment by readerneu** [comment] 2015-10-18 08:27
1. Following the suggestions on http://latex-community.org/forum/viewtopic.php?f=50&t=11447 I solved my problem. So for me no further date fromatting is needed.
2. Setting the ascii option was also helpful

So thank you very much the Bibliography is working fine now!

**Comment by retorquere** [comment] 2015-10-18 09:53
Cool, thanks for the feedback.

**Closed by retorquere** 2015-10-18 09:53 UTC
Labels: question
