### ISSUE TITLE
Problem with better biblatex "An error occured while trying to export the selected file"

### ISSUE THREAD

**Issue by vanderlindenma** [ZotPlus/zotero-better-bibtex#134] opened 2015-01-21 20:28 UTC
Report ID on firefox plugin :138926557

Report ID on standalone : 1700080976

I suddenly cannot export using better bibtex. Things worked just fine this morning. It really looks like better bibtex is not installed anymore
although the add-on pane says it is (in zotero's preferences, the better biblatex tab is still there).

New problems which emerged at the same time :

- I used to be able to drag and drop an item from Zotero into Texstudio and get the corresponding \cite{}. This does not work anymore. When I drag and drop, nothing happens.
- When I left click on an item with no "extra" entry and ask to "Generate Bibtex key" nothing happens.
- Although I checked the "Show citekey instead of 'extra' field in reference list" (and restarted multiple times) the 'extra' field is still there.

Regular bibtex export still works fine too.

Thanks in advance for your help.

**Comment by AllThatIsTheCase** [comment] 2015-01-21 21:03
Unfortunately I cannot access the debug logs submitted through the internal reporting facilities. It looks like another plugin has auto-updated and introduced a conflict with BBT; it's happened before, but I can usually work around it. What you will have to do is the following:

1. Go into the Zotero preferences, tab "Advanced", check the box that says "Enable after restart". Click "OK"
2. Close Firefox (make sure *all* windows are closed)
3. Re-start Firefox
4. Go into the Zotero preferences, tab "Advanced", click "View output"
5. Click in the resulting window, press control-A (select-all), then control-C (copy)
6. Open a plain-text editor. On Windows, notepad would do the job. Paste the log just copied into it
7. Save the resulting text file, and drop it into https://dbinbox.com/allthatisthecase

Can you also get me a list of plugins you installed?

**Comment by vanderlindenma** [comment] 2015-01-21 21:13
Done, tell me if you did not get it.

As far as other plugins are concerned, I have ZotFile 4.1.1 installed on both the firefox and the standalone version. On the standalone, I also have Zotero Word for Mac Integration 3.5.6.SA.4.0.23, but from what I can tell, it is not installed on the firefox plugin. 

Many thanks for your quick reply and for offering a somewhat anonymous solution for log submission (would have been a pain to remove all personal information from this log).

**Comment by vanderlindenma** [comment] 2015-01-21 21:17
Ok, don't know why but now everything works fine again. Not sure if I the log was generated after or before things where back to normal. If it runs into trouble again, I follow the procedure once more and send you another log.

**Comment by AllThatIsTheCase** [comment] 2015-01-21 21:25
No problem. Strange, though. It looks like BBT is starting up normally, but BBT not showing any sign of life, it must bomb out fairly early. There are also zero exceptions in the log. I see Zotfile 4.1.1 released a few days ago, but I just installed it, and that in itself is not causing me any problems. 

Could you try opening "http://localhost:23119/better-bibtex/collection" in firefox? I expect you'd see "Could not export bibliography: no path".

**Comment by AllThatIsTheCase** [comment] 2015-01-21 21:26
Ah, sure, no problem. Don't hesitate to file a new issue -- I don't ever want my work to be the cause of disrupted flow.

**Comment by vanderlindenma** [comment] 2015-01-21 21:26
"Could not export bibliography: no path", as expected.

**Comment by AllThatIsTheCase** [comment] 2015-01-21 21:28
Unfortunately, the logging slows down Zotero to a noticeable degree, so you don't always want it on, but you need to have it on for me to be able to look at what's happening for things I can't reproduce here. I sure hope it's not a platform thing... although it *would* finally give me that excuse to get a macbook air...

**Comment by AllThatIsTheCase** [comment] 2015-02-02 09:23
Are you OK with closing this issue? It is never a problem to open a new one if the problem reappears.

**Comment by vanderlindenma** [comment] 2015-02-02 14:38
Yeah, sorry, should have done it much earlier. Thanks again for you help.

**Closed** 2015-02-02 14:38 UTC
