### ISSUE TITLE
Better bibtex: url export does not survive underscores

### ISSUE THREAD

**Issue by murmlgrmpf** [ZotPlus/zotero-better-bibtex#402] opened 2015-11-17 15:38 UTC
I have a url containing an underscore in my references. When I compile the document, latex tries to interpret it as a subscript.

**Comment by retorquere** [comment] 2015-11-17 15:55
Can you right-click that reference for me and select "report BBT error"? That will get me your reference as a test case.

**Comment by murmlgrmpf** [comment] 2015-11-17 16:17
sorry, submitting the error does not work, it gives me an error dialogue:
Invalid response from repository: 403: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>DD1429A1B60CCB27</RequestId><HostId>IQQtSqT+UB3mAH4OcV2jNmiXT75uTinGnF3RhpBC1mBq1s9fbQ4RW+SWvhaSIuQc7xOSI0dKuuc=</HostId></Error>

**Comment by murmlgrmpf** [comment] 2015-11-17 16:18
Shall I post the messages per copy paste?

**Comment by retorquere** [comment] 2015-11-17 16:23
Argh, I hate AWS some days. Can you export to "BetterBibTeX JSON" format and drop the resulting file into https://dropitto.me/retorquere? The password is "none", without the quotes.

**Comment by retorquere** [comment] 2015-11-17 21:05
I've found the S3 problem with the reporting, that will be fixed in the next release. In the meantime, if you can get me that reference, I can look into your URL problem.

**Comment by murmlgrmpf** [comment] 2015-11-18 06:54
I have uploaded the reference. Thanks for having a look at it.
Btw: I noticed that escaping \ works -> \\ (because I have tried to manually escape the underscore)

**Comment by retorquere** [comment] 2015-11-18 09:33
If you surround the text with back-quotes github won't escape stuff.

I tried your reference exported with the current Better BibLaTeX, and it renders to:

```
Thomas Emmert et al. taX - a Flexible Tool for Low-Order Duct Acoustic Simulation in Time and Frequency Domain." In:7th  Forum  Acusticum.Krakow, Sept. 2014.url:http://www.fa2014.agh.edu.pl/fa2014_cd/
```

The current MWE is at https://www.sharelatex.com/project/54feca38f58d781e0c982eeb; can you reproduce the error there?

**Comment by murmlgrmpf** [comment] 2015-11-18 09:54
I am using Better BibTex and BibTex to translate the bibliography. Should I
switch the procedure or is better bibtex supposed to handle this workflow?


retorquere <notifications@github.com> schrieb am Mi., 18. Nov. 2015 um
10:33 Uhr:

**Comment by retorquere** [comment] 2015-11-18 09:57
BibLaTeX is better, but both ought to work. Can you change the MWE to BibTeX?

**Comment by murmlgrmpf** [comment] 2015-11-18 10:23
I am confused, I am using Bibtex for export and Latex.
You told me you could not reproduce the error using BibLAtex.

Did you want to ask me to change to biblatex instead?

**Comment by murmlgrmpf** [comment] 2015-11-18 10:30
The .bib file gives me the following:
@inproceedings{EmmerJaens14a,
  address = {Krakow},
  title = {{taX} - a {Flexible} {Tool} for {Low}-{Order} {Duct} {Acoustic} {Simulation} in {Time} and {Frequency} {Domain}},
  url = {http://www.fa2014.agh.edu.pl/fa2014_cd/},
  abstract = {Low order duct acoustic models are a powerful tool to predict and avoid aeroacoustic instabilities like whistling. Such instabilities are important in the development process of many applications as diverse as pipeline networks, mufflers or HVAC Systems. This paper presents a low order network duct acoustic simulation tool called taX, which takes advantage of the Matlab control system toolbox. The propagation of acoustic perturbations may be modeled by a set of linear, time invariant differential equations. By simplification to one dimensional propagation of acoustic waves, the acoustic system can be modeled by Green's functions describing the transmission of acoustic waves in a network of acoustic elements. The scattering of acoustic waves in each of the acoustic elements can be respresented by the scattering matrix, which is the Fourrier transformation of the Green's function. We demonstrate that there exists an equivalence between the aeroacoustic models and system description and commonly used models of control sytem theory. Being aware of this analogy, we have the opportunity to leverage the power of control system theory and future developments in this field to solve duct acoustic problems. Our tool therefore takes advantage of efficient implementations given by the Matlab control system routines. Subsequently the tool will be applied to determine the acoustic stability of a simple acoustic network model comprising an area jump, two duct sections, and open ends. The acoustic models involved are analytically derived from first principles in continuous time. In order to demonstrate the versatility of the tool set, a bifurcation diagram for decreasing area ratios of the orifice is computed and discussed. Further we will show the seamless integration of discrete time models retrieved by system identification from random time series data in LES simulations. The identified model of an area jump is compared to the model retrieved from first principles, limitations of the analytical model are discussed. In order to do so, the eigenvalues of the discrete time system are transformed to match and therefore compare to the eigenvalues of the continuous time system.},
  timestamp = {2015-11-17T15:46:16Z},
  booktitle = {7th {Forum} {Acusticum}},
  author = {Emmert, {Thomas} and {Jaensch}, {Stefan} and {Sovardi}, {Carlo} and {Polifke}, {Wolfgang}},
  month = sep,
  year = {2014},
  keywords = {NonPerRev},
  file = {Emmert et al_2014_taX - a Flexible Tool for Low-Order Duct Acoustic Simulation in Time and.pdf:/home/thomas/Documents/Zotero/storage/3VZKQZD7/Emmert et al_2014_taX - a Flexible Tool for Low-Order Duct Acoustic Simulation in Time and.pdf:application/pdf;Emmert+_2014_taX - a Flexible Tool for Low-Order Duct Acoustic Simulation in Time and.pdf:/home/thomas/Documents/Zotero/storage/DWJ3XIRI/Emmert+_2014_taX - a Flexible Tool for Low-Order Duct Acoustic Simulation in Time and.pdf:application/pdf}
}

and the .bbl:
\bibitem[{Emmert et~al.(2014)Emmert, {Jaensch}, {Sovardi}, and
  {Polifke}}]{EmmerJaens14a}
\bibinfo{author}{T.~Emmert}, \bibinfo{author}{S.~{Jaensch}},
  \bibinfo{author}{C.~{Sovardi}}, \bibinfo{author}{W.~{Polifke}}, in:
  \bibinfo{booktitle}{7th {Forum} {Acusticum}}, \bibinfo{address}{Krakow}.
  \URLprefix \url{http://www.fa2014.agh.edu.pl/fa2014_cd/}.

Subsequently pdflatex fails to compile as it interprets the underscore as a subscript, switches to mathmode and messes things up.

**Comment by retorquere** [comment] 2015-11-18 10:40
No, sorry, I didn't explain that well enough. The MWE I put up uses BibLaTeX, and that works as expected. If you could change the MWE to use BibTeX instead to reproduce the error, I can see where it goes wrong.

**Comment by retorquere** [comment] 2015-11-18 10:44
I have already pasted in the Better BibTeX export instead of the Better BibLaTeX export, but since I don't use BibTeX myself, I don't know how to configure the MWE to use BibTeX instead of BibLaTeX.

**Comment by retorquere** [comment] 2015-11-18 12:18
I've tried changing it to BibTeX, but the URL doesn't appear and it still compiles.

**Comment by murmlgrmpf** [comment] 2015-11-18 13:25
I got it broken ;-)
Just changed the bibliographystyle to something that shows the url.

**Comment by murmlgrmpf** [comment] 2015-11-18 13:26
and boiled it down a bit.

**Comment by retorquere** [comment] 2015-11-18 15:26
Super, thanks!

**Comment by retorquere** [comment] 2015-11-18 15:30
@nickbart1980, neither  BibTeXing nor Tame the BeaST mention how URLs ought to be encoded for BibTeX, any insights? If the `_` is invalid without escaping in a BibTeX reference I'm inclined to think it needs just regular LaTeXification.

**Comment by murmlgrmpf** [comment] 2015-11-18 15:37
pardon me, I admit I cannot help you, as I do not know the specs ;-)

But I know that putting a \ upfront the string fixes my problem, see the mwe.

**Comment by murmlgrmpf** [comment] 2015-11-18 15:39
Surplus: if i put a \ upfront the underscore in Zotero, when exporting with betterbibtex, it is adding a second backslash to escape the first. i.e. betterbibtex seems to Latexify the url string, but it misses the underscore. Maybe this is a general issue of the Latexification procedure not being aware of underscores?

**Comment by murmlgrmpf** [comment] 2015-11-18 15:41
So I guess you are right, it needs regular LaTeXification.

**Comment by retorquere** [comment] 2015-11-18 15:45
@murmlgrmpf the URL encoder currently encodes to what is called LaTeX verbatim mode; it's not entirely unescaped, but very little is touched. @nickbart1980 is my current go-to guy when it comes to the intricacies of Bib(La)TeX; I know my way around javascript, but LaTeX is a deep mistery to me. [Tests are running](https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/91843478) on a change that LaTeXifies for BBT but does verbatim encoding for BBLT.

**Comment by retorquere** [comment] 2015-11-18 15:55
And [again](https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/91845646)

**Comment by retorquere** [comment] 2015-11-18 16:01
Tests pass, so I'm giving @nickbart1980 a little time to chime in and I'll cut a release then.

**Comment by nickbart1980** [comment] 2015-11-18 17:21
Latexification of URLs is not the right approach, I’d say.

The recommended approach for bibtex is 

~~~
howpublished = "\url{…}",
~~~

You have to load `\usepackage{url}` or `\usepackage{hyperref}` in your main `.tex` file, of course.

See, e.g., https://tex.stackexchange.com/questions/35977/how-to-add-a-url-to-a-latex-bibtex-file.

biblatex has a dedicated `url` field (and, just in case this wasn’t clear anyway, no latexification must be applied here either).

**Comment by retorquere** [comment] 2015-11-18 18:04
If you don't have either of those loaded, will the document fail to compile?

**Comment by retorquere** [comment] 2015-11-18 18:09
tests are [running](https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/91872937) again, but I expect this to break a few cases.

**Comment by retorquere** [comment] 2015-11-18 18:46
Yeah, this breaks compilation if you don't have those packages enabled, so it goes behind a pref.

**Comment by retorquere** [comment] 2015-11-18 18:52
@nickbart1980 if I use the 'howpublished' method with the IEEEtran style, the URL doesn't show at all.

**Comment by retorquere** [comment] 2015-11-18 18:53
(MWE at https://www.sharelatex.com/project/54feca38f58d781e0c982eeb)

**Comment by nickbart1980** [comment] 2015-11-18 22:22
`howpublished` works in `@misc` (and `@booklet`) only; for `@inproceedings` and all other types, try the `note` field.

**Comment by retorquere** [comment] 2015-11-19 12:31
@murmlgrmpf does this fit your need?

**Comment by retorquere** [comment] 2015-11-19 13:30
@nickbart1980 what is the advantage of `note = {\url{http://...}}` over `note = {http://...}` (assuming both are correctly escaped?) other than that the one is clickable? If no other difference, I could just make clickability the preference rather than having the preference drive presence of the url.

**Comment by retorquere** [comment] 2015-11-19 13:32
What does this mean for `urldate` in BibTeX BTW?

**Comment by retorquere** [comment] 2015-11-19 13:34
Is the solution proposed in #401 correct? Should I do `lastchecked` instead of `urldate` (and does this apply to all reference types?)

**Comment by retorquere** [comment] 2015-11-19 14:16
Neither BibTeXing nor Tame The BeasT mention `lastchecked`. Is there any form of standard here? Some answers on tex.stackexchange.com recommend stuffing it in a note field, that seems a little hacky.

**Comment by murmlgrmpf** [comment] 2015-11-19 15:06
I am unsure, what your final solution was, thus I cannot really say whether it fixes my problem or not...
Can you please specify, what you are planning to do/ what howpublished vs. note means (is this the way the fields are formated/escaped?)

**Comment by nickbart1980** [comment] 2015-11-19 15:13
First, I feel no one would can avoid it should be using bibtex any longer. URLs and URL dates in particular are a complete mess. That being said, `\url{}` has the advantage that you do not need to change/encode/latexify the URL in any way, *and* you can render it as clickable; hence this seems to be the generally accepted solution; see many posts on TSE etc. Unless, that is, you are using natbib (and possibly other) bibtex styles that do have a `url` field.

**Comment by murmlgrmpf** [comment] 2015-11-19 15:33
The reason we are using bibtex is that we are publishing in elsevier journals and proceedings. Unfortunately they require you to upload tex code that is compiled on their build server. Thus there is no choice to switch to biblatex.
Given that the bibtex procedure is outdated and not recommended for use, I would suggest to look for a procedure that fits for the majority of usecases, where bibtex is needed.

**Comment by nickbart1980** [comment] 2015-11-19 15:39
Fair enough, but that precisely would be my question: What are Elsevier recommending for URLs and URL dates?

**Comment by retorquere** [comment] 2015-11-19 15:41
LaTeXifying is easy enough; and while biblatex is of course better, but
bibtex still serves a purpose.

I don't want to output anything by default that requires specific packages.
I'm keeping it as an option.

How about access date? Is that only for websites? And what field is
appropriate?

**Comment by murmlgrmpf** [comment] 2015-11-19 15:50
I didn't find any specific recommendations by Elsevier. In the end, I suppose it is not important for them, as they are reformating everything anyway (they are compiling websites with all kinds of links etc. with the latex code).
So I suppose best is to have a simple option for bibtex to export the url field without need for an additional package. Elsevier is doing their business on the code anyway and those who have the choice use biblatex.

**Comment by retorquere** [comment] 2015-11-19 19:41
So... what's the consensus for url and accessdate in BibTeX?

**Comment by murmlgrmpf** [comment] 2015-11-19 19:54
I dont know about accessdate.
I suggest to fix the urls for bibtex export such that they are translated properly without any packages.

**Comment by retorquere** [comment] 2015-11-19 20:11
That still leaves 3 options:

1. Drop URLs for BibTeX
2. Encode as `note = {<latex code>}`
3. Encode as `note = {\url{<verbatim code>}}`

Each of them has their downsides:

1. Data discarded
2. Stuffs data in a field it doesn't really belong (putting it in a note is a hack, and the BibTeX exporter also exports the Zotero extra field in a note field; if you make the style display notes to show URLs, you also get everything in the extra field)
3. All of 2. *and* introduces a package dependency (and I've been there trying to get out of package-conflict-hell -- I don't want to be the source of the problem). But you get clickable URLs, which seems something you'd want to have if only as an option.

Of course I could leave this choice to the user by offering a tri-state preference, but that's one more preference in an already baroque preference pane for what was once just a simple translator. If I can get consensus on a behavior that doesn't require such a preference this has my strong preference. But since I don't use BibTeX myself, I can't really decide without input. It looks like @murmlgrmpf gravitates towards always-2; @nickbart1980, you?

**Comment by murmlgrmpf** [comment] 2015-11-19 20:25
I guess most of the time, there is doi anyway and in my opinion, there is no good reason to post a url plus a doi. (You wanted to have reduced preference plane? ;-)) So this really is a rare case, when a publication does not have a proper doi, but there is a url where you can download the papers or access the reference.
In addition, it is only cause for concern with bibtex, which is superseded and only used in some rare cases (mediocre build systems of publishers).

Thus I would opt for 2 and if someone really needs bibtex+ clickable urls he needs to include the url package and patch the .bib or .bbl files (the way I do atm.).

**Comment by retorquere** [comment] 2015-11-19 20:39
The DOI/URL thing is down to the same choice: if I drop data on the floor that the user has entered, I don't want to do that without user consent.

I'm OK with two myself (seeing as how I don't use BibTeX), but @nickbart1980 seems to prefer 3, and as said, he's my knowledge base and conscience when it comes to doing the right thing (or at least the best one can do under the circumstances that BibTeX and BibLaTeX impose), so I'd love to also have his opinion.

You don't even have to patch the bib/bbl files to get [clickable URLs](https://github.com/ZotPlus/zotero-better-bibtex/wiki/Scripting-examples) in any case.

**Comment by murmlgrmpf** [comment] 2015-11-20 06:44
Are you sure that there is real world usecases where doi+url are useful? I mean doi is a link to the url where the object is found!? Why would you want to have another link?

**Comment by retorquere** [comment] 2015-11-20 07:01
I'm not at all sure, but then absence of evidence is not evidence of
absence. My running assumption is that if a user has entered some data
there must be a reason for its presence,and I just can't categorically
assume this to be an error.

**Comment by murmlgrmpf** [comment] 2015-11-20 07:09
When you use the webimport plugin with zotero, it automatically stores the url and the doi. So I suppose in most cases when there is both, this is due to the webimporter and not due to an active decision.

**Comment by retorquere** [comment] 2015-11-20 08:12
Wait, what? That is fairly dense. Why would it do that?

**Comment by murmlgrmpf** [comment] 2015-11-20 08:18
God's ways are inscrutable - just as those of the webimporter ;-)

**Comment by murmlgrmpf** [comment] 2015-11-20 08:19
When you use the "Save to Zotero" browser plugin, it stores all the bibliography information plus the url where it retrieved it. When there is a doi, you get url+doi.

**Comment by nickbart1980** [comment] 2015-11-20 10:11
Just to be clear about this: I don’t use bibtex myself, so active users, or those forced to use it, might see things very differently. 

Just dropping a field as important as URL I feel is not an option at all. My general feeling is that programs should mess with URLs as little as possible, so I’d always prefer `note = {\url{<verbatim code>}}` over `note = {<latex code>}`. Anyone smart enough to use BBT should be able to load the `url` or `hyperref` package. This, it seems, would work with all legacy styles, and, as I said, seems to be the most popular choice on TSE. There is no equally clear advice on urldate or doi for bibtex, however.

An alternative would be to essentially follow biblatex, and use `url`, `urldate`, and `DOI` fields. natbib does understand `url` (but nothing else). Of course, users would have to tweak their bib files themselves, but with so many different use scenarios and legacy styles, many users will have to do this regardless of what solution BBT adopts in the end. If nothing else, a bib file with `url`, `urldate`, and `DOI` would be the clearest and easiest basis for individual tweaks.

As to DOI vs. URL: All CSL styles, as well as biblatex styles (I tested authoryear, apa, chicago) do not render the URL if an entry contains a DOI, too; so keeping the URL typically is not a problem.

**Comment by murmlgrmpf** [comment] 2015-11-20 10:25
Thus my issue is essentially resolved: 
\usepackage{url}
 is the answer.

**Closed** 2015-11-20 10:25 UTC
Labels: bug

**Comment by retorquere** [comment] 2015-11-20 22:24
So you don't actually want the change? Should I just keep the current behavior where the url is exported in the `url` field for BibTeX?
