### ISSUE TITLE
Automatic export when idle triggered immediately at every change

### ISSUE THREAD

**Issue by smatthie** [ZotPlus/zotero-better-bibtex#232] opened 2015-07-05 08:33 UTC
I have the automatic update set to "when idle", but it seems to export immediately as soon as I change anything. When I do multiple changes at once (e.g. move several articles into a collection) then it exports the library several times, making firefox unresponsive for minutes (I export the whole library, 5000 entries).

I'm not sure if I perhaps misunderstand the "when idle" setting, but I had expected it would export when I haven't done any changes for a few minutes or something like that.

Using Better Bibtex 0.14.6, Zotero 4.0.27.2, Zotfile 4.1.6, Firefox 38.0, Ubuntu 14.05

**Comment by retorquere** [comment] 2015-07-05 08:40
Your expectation is exactly correct, so it looks like you've found a bug.
Could you enable debugging in the better bibtex preferences "debug" tab,
then trigger the behavior by making a change, and then sending me the debug
log using "send ZotPlus error" from the gear menu. If you post the debug id
here, I can look at the problem in detail. I'll try to reproduce here too,
but having an insight in what's happening on your end is usually very
helpful.

**Comment by smatthie** [comment] 2015-07-05 09:55
Thanks. i sent the debug log but I'm not sure if this worked, as I did get a connection error in the end. I will try to do it again. 

For the test, I imported the following two articles, using Zotero's translator button in the toolbar:
 
http://cdp.sagepub.com/content/24/1/77
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0124596

For each article, the library was exported 4 times in a row, the first export started at the moment when I pressed the translator button (I could see the file size of the bibfile go from 0 to 7Mb, then 0 again, repeated four times - each export takes about 2 minutes). Looking at Zotero's popup window (that shows the import progress), my guess is that separate exports happen when (1) the metadata is imported, (2) the file is attached, (3) the file is renamed.

**Comment by smatthie** [comment] 2015-07-05 10:33
Will try to send bug report tomorrow. Today I get the error "no valid response from repository" every time.

**Comment by retorquere** [comment] 2015-07-05 11:43
That is crazy, it would mean either that Amazon S3 is down, or that the debug log exceeds 20MB. I'll up the limit to 40, but at 20MB, there'd be a crazy amount of activity. And yes, each of those would trigger an export, but the idle trigger should bunch those together into one actual export.

**Comment by retorquere** [comment] 2015-07-05 11:55
Can you try the version at http://zotplus.github.io/better-bibtex/#debug, and generate a debug log from that? It has more detailed logging.

**Comment by retorquere** [comment] 2015-07-05 12:02
I can't yet reproduce the behaviour. When I import the above in a fairly large (2K items) library, I see in the logs that it triggers but defers the export, which is as I would have expected.

**Comment by smatthie** [comment] 2015-07-05 12:45
Log is larger than 20Mb, I can see in my network graph that it sends 20Mb and then gets the error. I'll try the debug version.

I noticed another thing: When I restart Firefox, at first it works as expected (I can add, edit, delete a few items without triggering an export). But at some point, after a few changes, it suddenly starts to export like crazy as described above.

**Comment by retorquere** [comment] 2015-07-05 13:39
The version that is on the link above has all log trimming disabled, so the size of the log should't be an issue; it also cuts down on about 4mb of startup chatter that isn't going to be relevant for this case.

**Comment by retorquere** [comment] 2015-07-05 13:41
(the debug version was updated at the time of the comment above this one, so updated against the version of two hours before that)

**Comment by retorquere** [comment] 2015-07-05 13:48
Regardless of all of that, either version will have lines in the log stating

    auto.process: started (...), idle: ...

where the first `...` states the trigger (something like 'idle', 'itemChanged' etc), and the second `...` will be either `false` or `true`, which indicates what BBT thinks the idle state is at the time that line was logged. In your case it should be usually followed by:

    auto.process: not idle

which in sum total would for example be:

    auto.process: started (itemChanged), idle: false # itemChanged means we will want to auto-export
    auto.process: not idle # but not now, defer until idle
    ....
    auto.process: started (idle), idle: true # now's good.

**Comment by smatthie** [comment] 2015-07-05 15:16
I tried to upload the log again but even with 40Mb I get an error in the end. Is there a way for me to save the log as a file and look at it, or upload it somewhere else? The window (before sending the log) only shows a summary, doesn't it? The last lines shown in the window are:

> (3)(+0030791): [Sun, 05 Jul 2015 13:50:43 GMT better-bibtex] [DEBUG] idle: idle
> (3)(+0000000): [Sun, 05 Jul 2015 13:50:43 GMT better-bibtex] export cache: flush… (93 chars)
> (5)(+0000001): Beginning DB transaction
> (3)(+0000000): Beginning Notifier event queue
> (5)(+0000000): delete from betterbibtex.cache where lastaccess < datetime('now',… (91 chars)
> (5)(+0000001): Committing transaction
> (3)(+0000000): Resetting Notifier event queue
> (5)(+0000000): Beginning DB transaction
> (3)(+0000000): Beginning Notifier event queue
> (5)(+0000000): Committing transaction
> (3)(+0000000): Resetting Notifier event queue
> (3)(+0000000): [Sun, 05 Jul 2015 13:50:43 GMT better-bibtex] [DEBUG] auto.proces… (109 chars)
> (3)(+0000000): [Sun, 05 Jul 2015 13:50:43 GMT better-bibtex] [DEBUG] auto.proces… (86 chars)
> (3)(+0004753): [Sun, 05 Jul 2015 13:50:48 GMT better-bibtex] [DEBUG] idle: activ… (81 chars)
> (3)(+0019969): [Sun, 05 Jul 2015 13:51:08 GMT better-bibtex] [DEBUG] idle: idle
> (3)(+0000000): [Sun, 05 Jul 2015 13:51:08 GMT better-bibtex] export cache: flush… (93 chars)
> (5)(+0000000): Beginning DB transaction
> (3)(+0000001): Beginning Notifier event queue
> (5)(+0000000): delete from betterbibtex.cache where lastaccess < datetime('now',… (91 chars)
> (5)(+0000001): Committing transaction
> (3)(+0000000): Resetting Notifier event queue
> (5)(+0000000): Beginning DB transaction
> (3)(+0000000): Beginning Notifier event queue
> (5)(+0000000): Committing transaction
> (3)(+0000000): Resetting Notifier event queue
> (3)(+0000001): [Sun, 05 Jul 2015 13:51:08 GMT better-bibtex] [DEBUG] auto.proces… (109 chars)
> (3)(+0000000): [Sun, 05 Jul 2015 13:51:08 GMT better-bibtex] [DEBUG] auto.proces… (86 chars)
> (3)(+0011090): [Sun, 05 Jul 2015 13:51:19 GMT better-bibtex] [DEBUG] idle: activ… (81 chars)
> (3)(+0018057): [Sun, 05 Jul 2015 13:51:37 GMT better-bibtex] [DEBUG] idle: idle
> (3)(+0000001): [Sun, 05 Jul 2015 13:51:37 GMT better-bibtex] export cache: flush… (93 chars)
> (5)(+0000000): Beginning DB transaction
> (3)(+0000000): Beginning Notifier event queue
> (5)(+0000000): delete from betterbibtex.cache where lastaccess < datetime('now',… (91 chars)
> (5)(+0000000): Committing transaction
> (3)(+0000001): Resetting Notifier event queue
> (5)(+0000000): Beginning DB transaction
> (3)(+0000000): Beginning Notifier event queue
> (5)(+0000000): Committing transaction
> (3)(+0000000): Resetting Notifier event queue
> (3)(+0000000): [Sun, 05 Jul 2015 13:51:37 GMT better-bibtex] [DEBUG] auto.proces… (109 chars)
> (3)(+0000001): [Sun, 05 Jul 2015 13:51:37 GMT better-bibtex] [DEBUG] auto.proces… (86 chars)
> (3)(+0000627): [Sun, 05 Jul 2015 13:51:37 GMT better-bibtex] [DEBUG] idle: activ… (81 chars)
> (3)(+0030684): BBT.error.init
> (3)(+0000000): BBT.error.init: RVESXEHE-RAGK8FPQ
> (3)(+0000000): BBT.error.init: here we go

**Comment by smatthie** [comment] 2015-07-05 15:44
I finally managed to upload a log: VG8MRDVG-55CSEZQJ

**Comment by retorquere** [comment] 2015-07-05 18:36
It seems to think it's always idle. I've removed all log size restrictions on the receiving side; can you try to

1. check the debug checkbox in the BBT debug preferences
2. install zotero-better-bibtex-0.14.7-2015-07-05@20:31:37.xpi from the above link and let it restart firefox
3. trigger an auto-export
4. submit the log

It won't fix it, but it has extra debug logging will hopefully give me insight on why it thinks it's always idle.

**Comment by smatthie** [comment] 2015-07-05 21:11
Thanks for your help. New log with the new debug version: V4V6UVQ7-W4JWAEVX

This time i could import 4 articles without problems (again with the Zotero button from the journal websites), but on the 5th and 6th article it did the multiple continuous export.

**Comment by retorquere** [comment] 2015-07-05 21:22
If you look in `about:config`, what is `extensions.zotero.translators.better-bibtex.autoExportIdleWait` set to?

**Comment by retorquere** [comment] 2015-07-05 21:32
I'm sorry I have to ask this, but are you sure you closed all firefox windows after installing zotero-better-bibtex-0.14.7-2015-07-05@20:31:37.xpi ? There are no log statements for the idle observer (which I added in that version), yet it must at some point have been called, as the auto-exporter starts up assuming it's not idle. It must have been set to idle actively at some point, but I don't see any indication of that in the new logs.

**Comment by smatthie** [comment] 2015-07-05 21:50
Hmm, I thought I restarted firefox after installing, but to make sure I'll try again and upload a new log...

**Comment by smatthie** [comment] 2015-07-05 23:13
Next one: GPFA2DFW-UBF4ZJXS Let me know if it worked this time, or if I should try something else. Thanks again for your help!

**Comment by retorquere** [comment] 2015-07-05 23:50
OK, that makes slightly more sense... at least I see the idle manager kicking in, BBT just inexplicably thinks Firefox is idle by default. I have put up zotero-better-bibtex-0.14.7-2015-07-06@01:47:49.xpi , which explicitly sets idle to false at startup, could you try that (and put up a new log)?

**Comment by retorquere** [comment] 2015-07-05 23:52
(oh and yes, the window only shows a summary)

**Comment by smatthie** [comment] 2015-07-06 06:34
New log: TPJ524K6-F3GZHZZ4 (much smaller file now...)
But the newest version has broken export completely. It doesn't start an automatic export  even after several imports, but I can't even export entries manually (Error: "Ein Fehler ist aufgetreten bei dem Versuch, die ausgewählte Datei zu exportieren."). Also, in the BBT settings there is an additional empty tab with the title "Better BibTex has been disabled", and the citation keys are empty.

**Comment by retorquere** [comment] 2015-07-06 08:58
My apologies; that build contained an error. zotero-better-bibtex-0.14.7-2015-07-06@10:57:52.xpi fixes that and has the additional logging.

**Comment by smatthie** [comment] 2015-07-06 09:46
Thanks, no problem, happy to test. New log: BB3UJ6PP-MJ3TBA2H
This time it works basically as I would expect.
* I added 8 articles. The only odd thing was that it did one single automatic export while I added the 4th article, but it was only one export, not the multiple cycle, and then was quiet again for the other edits. 
* I then went away for a few minutes to have it really idle, and after about 5 minutes it did an automatic export in the background. 
* Then I added another article and did some more edits, no automatic export triggered while I was working. 
* I left it again for a few minutes, and again it did an automatic export after about 5 minutes.

**Comment by retorquere** [comment] 2015-07-06 11:38
I have no idea why, but explicitly setting the state to idle rather than letting it be undefined (which is falsish in javascript) seems to do the job then. Could you have one more go at it with zotero-better-bibtex-0.14.7-2015-07-06@13:35:29.xpi ? If that works, and I can see in a new log that it does he right things, I'll release a new version. Apologies for all the extra work I'm causing you, but I haven't been able to reproduce it on my own systems.

**Comment by retorquere** [comment] 2015-07-06 11:41
Sorry, that should be zotero-better-bibtex-0.14.7-2015-07-06@13:40:25.xpi . A new log might also tell me why that extra auto-export did happen.

**Comment by retorquere** [comment] 2015-07-06 12:08
I've fixed another (probably unrelated bug) so the test xpi is now zotero-better-bibtex-0.14.7-2015-07-06@14:07:12.xpi

**Comment by smatthie** [comment] 2015-07-06 12:49
New log (produced with the 14:07:12 version): 6ZMHBX7K-Q9CD7KA7
This time I imported 12 items (no autoexport), then went away (autoexport after a few minutes), then 2 more (no autoexport). Just while I was writing this, it did another autoexport (won't be in the log). Exactly as it should be.

Thanks for your work - no problem for me to test, I have a long list of literature that I need to import into Zotero anyway, so this testing is a good opportunity for me to do it and get my reference list up to date!

**Comment by retorquere** [comment] 2015-07-06 13:23
Superb -- I like what I see in the log. I depend on users lie you to iron these out, so really -- thank you for sticking this one out. You can disable the debug logging, I've scheduled a new release, should be out soon.

**Closed by retorquere** 2015-07-06 13:23 UTC

**Comment by smatthie** [comment] 2015-07-06 13:29
Cool. Thanks again for your work! I'm happy to help, I know how difficult it is to find bugs when you can't reproduce them on your own system, as is often the case.

**Comment by retorquere** [comment] 2015-07-06 14:47
0.14.10 is out
