### ISSUE TITLE
Firefox disabled BBT

### ISSUE THREAD

**Issue by verwinv** [ZotPlus/zotero-better-bibtex#390] opened 2015-10-28 09:38 UTC
Hi, Hope I'm not duplicating 1000 other issue requests, but I'm stuck in trying to resolve this:

Export library > "An error occurred while trying to export the selected file."
Report ZotPlus Errors > Can't find this item in the menu
zotero://debug/ > Empty page

What else can I do to resolve this?
Kind regards and thanks for your time.

**Comment by retorquere** [comment] 2015-10-28 09:43
Don't worry about duplication; I'd rather have a 1000 too many than one too few.

If there is no "Report ZotPlus error" in the Zotero gear menu, that means BBT has bombed out very early in the startup phase. If this is the case, I can still get a log, but I'll need to know what operating system (Windows, Linux, OSX?) you use. If you can tell me that, I can provide further instructions.

Once we get "Report ZotPlus Error" back,do the following:

1. Go into BBT preferences
2. Enable "extended debugging" in the "debug" section
3. Restart firefox
4. Send a report using "Send ZotPlus report" from the gear menu.

**Comment by verwinv** [comment] 2015-10-28 09:47
So sorry - Mac OSX 10.11, using Firefox 41.0.2.

**Comment by retorquere** [comment] 2015-10-28 10:01
Please don't apologise. My guiding documentation on these matters is not even near to complete.

Alright, I'll need you to get in touch with your inner geek. Close down firefox completely (so no dot on the FF icon in the doc), open a command line shell, then execute

```
/Applications/Firefox.app/Contents/MacOS/firefox-bin --ZoteroDebug | tee ~/Documents/390.log
```

A whole heap of text will scroll by, don't worry about that. Let firefox start up, open the Zotero pane, let the stream of text in the console settle, then full close FF again. The shell will return to the prompt, and there will be a file called `390.log` in your Documents folder. Drop that into https://dropitto.me/retorquere (the password is `none`, literally)

**Comment by verwinv** [comment] 2015-10-28 10:53
Inner geek executed. File has been dropped. Includes the words "warn" and "exception", which make my inner geek cringe.

**Comment by retorquere** [comment] 2015-10-28 11:07
Which version of Zutilo do you have installed? If I install 1.2.10.1 BBT complains loudly it isn't compatible.

I've installed the latest [beta version of Zutilo](https://github.com/willsALMANJ/Zutilo/releases), and with that Zotero starts up cleanly.

Can you try temporarily removing Zutilo to see whether it is indeed the interaction between BBT and Zutil that causes your problem? You'll need to remove Zutilo and fully restart FF (FF has the nasty habit of keeping running on OSX even though all FF windows are closed, so if there's still a dot on the doc, close it from the dock).

**Comment by retorquere** [comment] 2015-10-28 11:12
(BTW I'm sorry you felt you had to execute your inner geek; your inner geek can be a good friend even if he looks a little scraggly. In any case execution seems a little Michael Bayish :wink:)

**Comment by verwinv** [comment] 2015-10-28 11:26
- Uninstalled Zutilo (totally forgot to check the version number. I won’t apologise).
- Restarted FF (Command-Q’ing the programme, then launching again)
- Pressed ‘Export Library’ > Better Bibtex
- FF returned a prompt saying 'An error occurred while trying to export the selected file."

Still no ZotPlus functionality visible, and an empty page upon looking up "zotero://debug <zotero://debug>”.

**Comment by verwinv** [comment] 2015-10-28 11:28
(I'm never sure whether to pet that inner geek and let him flourish, or muffle any sounds it makes. Still undecided for now. Had I styled this message with Markdown it would have cried with joy. But I didn't.)

**Comment by retorquere** [comment] 2015-10-28 11:40
OK, that rules out Zutilo being the cause, although I'm still curious which version you have installed. If it's 1.2.10.1, which is the latest released version, there's no way for me to get it to work. That version of Zutilo has a [bug](https://github.com/willsALMANJ/Zutilo/issues/30) that stops other Zotero extensions that happen to initialize after it from starting up, leaving those extension in a half-initialized state, and I have no control over initialization order. The beta version corrects this bug.

For the interim, you'll have to pet your inner geek, because we'll need her again. Start Zotero, go into Zotero preferences, advanced and check "enable after restart". Close FF (and when I say that I will always mean "completely"), and do the 
```
/Applications/Firefox.app/Contents/MacOS/firefox-bin --ZoteroDebug | tee ~/Documents/390-2.log
```
spiel again. This time there ought to be reams of text.

You do realise that if you're at all interested in BibTeX, you're sort of feeding the inner geek? :stuck_out_tongue_winking_eye:

**Comment by verwinv** [comment] 2015-10-28 16:10
So apologies áre in place then. I removed the Zutilo add-on, so can’t see what its version nr. was.

No reams of text appeared. I opened Zotero, and even made another attempt at exporting the library, but the logfile remains eerily empty.

**Comment by retorquere** [comment] 2015-10-28 17:45
Nope, still no apologies.

On a minimal install (fresh ff profile, with only zotero extension installed, no extra debug logging), I still get something like [this](https://gist.github.com/0df6b43ec589d607b10f). I couldn't create that empty a log if I tried.

Could you try the following (please don't have anything of value open in firefox, as it will be shut down rather ungracefully):

```
killall 'firefox'
```

and then again
```
/Applications/Firefox.app/Contents/MacOS/firefox-bin --ZoteroDebug
```

Note that ZoteroDebug is case sensitive, and that there must be two dashes before it, not one. Best to paste the text into the shell. There really ought to be at minimum that `Using data directory` line -- Zotero can't have started at all unless it's there.

**Comment by retorquere** [comment] 2015-10-28 17:46
The "enable after restart" is unnecessary BTW since `--ZoteroDebug` implies debug logging.

**Comment by verwinv** [comment] 2015-10-28 17:50
I has fixed it. When I tried to just 'View Output' in the dialog, I saw the message "[JavaScript Error: "Zotero.BetterBibTeX is undefined" {file: "/Users/everbruggen/Library/Application Support/Zotero/Profiles/qdx1kblp.default/zotero/translators/Better BibTeX.js" line: 3409}]". Which made me reinstall BBT through the add-ons page. Which made me then reinstall the xpi. Upon which I then discovered Firefox simply disabled it for not being trustworthy. 

So now: everything works! And instead of a triumphant geek I feel like a grandmother who called the service desk to have them tell her she should plug in the telly before trying to switch it on.

Very happy to see the Zotero picker show up in Scrivener - the ultimate goal of this excercise. Now on to more geekery. And, ultimately, writing. Much thanks for your swift responses and caring!

**Comment by retorquere** [comment] 2015-10-28 18:00
Don't feel any kind of granny. Mozilla has instated a draconian new system where extensions must get their approval; there's a big upheaval about it, and Zotero is even threatening to leave Firefox altogether.

**Comment by retorquere** [comment] 2015-10-28 18:05
I'm guessing you're on FF34; you can sidestep this mess until FF44 by setting xpinstall.signatures.required in about:config to false. After that, I don't know.

**Comment by verwinv** [comment] 2015-10-28 18:06
FF41, good suggestion! Now off to pester davepwsmith to make me understand all that's not working with the Pandoc md conversion. Thanks so much for your swift responses and massive help!

**Comment by retorquere** [comment] 2015-10-28 18:14
Oh crap, is there still a version on the Mozilla  addons site? If there is, it's incredibly outdated.

**Comment by retorquere** [comment] 2015-10-28 18:34
Ah, now I know why you were seeing that error. The translators are still installed, but can't reach the extension. Usually, BBT removes the translators upon uninstall, but FF prevented it from starting up.

**Closed** 2015-10-29 08:08 UTC
Labels: question
