### ISSUE TITLE
Getting exports mixed up

### ISSUE THREAD

**Issue by vanderlindenma** [ZotPlus/zotero-better-bibtex#153] opened 2015-02-20 22:11 UTC
When using export library-Better Bibtex (with export notes and export collections checked) strangely gets (at least one) reference mixed up. The two following articles are part of my zotero library:

Prediction Market for Climate Outcomes, A
Type 	Journal Article
Author 	Shi-Ling Hsu
URL 	http://heinonline.org/HOL/Page?handle=hein.journals/ucollr83&id=181&div=&collection=journals
Volume 	83
Pages 	179
Publication 	University of Colorado Law Review
Date 	2011-2012
Extra 	bibtex: Hsu2011
Journal Abbr 	U. Colo. L. Rev.
Date Added 	1/20/2015, 10:17:21 AM
Modified 	1/20/2015, 3:13:20 PM

Efficient assignment respecting priorities
Type 	Journal Article
Author 	Lars Ehlers
Author 	Aytek Erdil
URL 	http://linkinghub.elsevier.com/retrieve/pii/S002205311000030X
Volume 	145
Issue 	3
Pages 	1269-1282
Publication 	Journal of Economic Theory
Date 	May 2010
Extra 	bibtex: Ehlers2010
DOI 	10.1016/j.jet.2010.02.007
Date Added 	1/12/2015, 9:45:30 AM
Modified 	1/12/2015, 10:31:48 AM

Now, in the exported bib file I get : 

@article{Hsu2011,
  title = {In search of advice for participants in matching markets which use the deferred-acceptance algorithm},
  volume = {48},
  issn = {0899-8256},
  url = {http://www.sciencedirect.com/science/article/pii/S0899825603002458},
  doi = {10.1016/j.geb.2003.09.007},
  abstract = {Many centralized entry-level labor markets use the firm-proposing deferred-acceptance (DA) algorithm to compute the matching that is implemented among workers and firms. We propose a definition of the strategic options a worker faces in the DA-algorithm. Then we develop a theory to advise workers who distinguish between the firms from which they believe not to receive a proposal, the firms from which they might receive a proposal, and the firms from which they certainly receive a proposal. If a worker is not able to deduce which new proposals she receives after having rejected others, then it is not profitable for her to submit a list that reverses the true ranking of any two acceptable firms. Furthermore, it is not beneficial for her to include a firm in her submitted list that is unacceptable to her.},
  number = {2},
  urldate = {2015-01-27},
  journal = {Games and Economic Behavior},
  author = {Ehlers, Lars},
  month = aug,
  year = {2004},
  keywords = {General truncation strategies,Incomplete information},
  pages = {249--270},
  file = {...}
}

and no entry for Ehlers2004.

**Comment by AllThatIsTheCase** [comment] 2015-02-20 22:26
Can you select those two references, right-click, and select "Report ZotPlus Error", and then post the displayed URL here?

**Comment by AllThatIsTheCase** [comment] 2015-02-20 22:30
Does this also happen if you export only these two entries BTW?

**Comment by vanderlindenma** [comment] 2015-02-20 22:33
Yes, when I export the two items only I get the following bibtex file : 


@article{Hsu2011,
  title = {In search of advice for participants in matching markets which use the deferred-acceptance algorithm},
  volume = {48},
  issn = {0899-8256},
  url = {http://www.sciencedirect.com/science/article/pii/S0899825603002458},
  doi = {10.1016/j.geb.2003.09.007},
  abstract = {Many centralized entry-level labor markets use the firm-proposing deferred-acceptance (DA) algorithm to compute the matching that is implemented among workers and firms. We propose a definition of the strategic options a worker faces in the DA-algorithm. Then we develop a theory to advise workers who distinguish between the firms from which they believe not to receive a proposal, the firms from which they might receive a proposal, and the firms from which they certainly receive a proposal. If a worker is not able to deduce which new proposals she receives after having rejected others, then it is not profitable for her to submit a list that reverses the true ranking of any two acceptable firms. Furthermore, it is not beneficial for her to include a firm in her submitted list that is unacceptable to her.},
  number = {2},
  urldate = {2015-01-27},
  journal = {Games and Economic Behavior},
  author = {Ehlers, Lars},
  month = aug,
  year = {2004},
  keywords = {General truncation strategies,Incomplete information},
  pages = {249--270},
  file = {Ehlers_2004_In search of advice for participants in matching markets which use the.pdf:/Users/martinvanderlinden/Copy/Literature/storage/454XJSN6/Ehlers_2004_In search of advice for participants in matching markets which use the.pdf:application/pdf;ScienceDirect Snapshot:/Users/martinvanderlinden/Copy/Literature/storage/N9MIDB3A/S0899825603002458.html:text/html}
}

@article{Hsu2011,
  title = {Prediction Market for Climate Outcomes, A},
  volume = {83},
  url = {http://heinonline.org/HOL/Page?handle=hein.journals/ucollr83\&id=181\&div=\&collection=journals},
  journal = {University of Colorado Law Review},
  author = {Hsu, Shi-Ling},
  year = {2011},
  pages = {179},
  file = {Law Journal Library - HeinOnline.org:/Users/martinvanderlinden/Copy/Literature/storage/TM5K4WM5/Page.html:text/html}
}

**Comment by vanderlindenma** [comment] 2015-02-20 22:34
http://goo.gl/FwtRxf

**Comment by AllThatIsTheCase** [comment] 2015-02-20 22:37
Can you upgrade to 0.7.27, and then report those two entries again?

**Comment by vanderlindenma** [comment] 2015-02-20 22:41
That's weird, both my firefox and standalone zotero tell me I am already running 0.7.27. I guess if you mention it is that it does not show up in the error log?

**Comment by AllThatIsTheCase** [comment] 2015-02-20 22:44
I don't know how Firefox could be wrong about this, so I'd sooner suspect my reporting, but the error log shows this:

    version => 4.0.26, platform => MacIntel, oscpu => Intel Mac OS X 10.10, locale => en-US, appName => Zotero, appVersion => 4.0.26, extensions => ZotFile (4.1.3, extension), Zotero Word for Mac Integration (3.5.7.SA.4.0.26, extension), Zotero Better Bib(La)Tex (0.7.23, extension), Google Talk Plugin Video Renderer (5.40.2.0, plugin), Google Talk Plugin (5.40.2.0, plugin), Java Applet Plug-in (Java 8 Update 31, plugin), Default Browser Helper (600, plugin), SharePoint Browser Plug-in (14.4.7, plugin), QuickTime Plug-in 7.7.3 (7.7.3, plugin), Shockwave Flash (11.8.800.94, plugin), Microsoft Office Live Plug-in (12.3.6, plugin), Zotero LibreOffice Integration (3.5.9.SA.4.0.26, extension, disabled)

and the report included what I think is your whole library, a bug in the error reporting that was fixed in .25

Could you try to force an update, restart FF, and send a report on those two entries again?

**Comment by AllThatIsTheCase** [comment] 2015-02-20 22:52
The error report window show show two separate panes before you submit -- one that would have the version info, the other the references that will be submitted. If you don't see those two panes, you're definately not on .27

**Comment by vanderlindenma** [comment] 2015-02-20 22:57
http://goo.gl/hhpx35

The error window does feature two panes now, which is encouraging. Unfortunately the problem persists. 

In the process, I have tried to export the two items with firefox-zotero instead of the standalone. Surprisingly, the problem is different with firefox, which generated the following bib file (articles ok, but weird reference):

@article{zotero-null-329,
  title = {In search of advice for participants in matching markets which use the deferred-acceptance algorithm},
  volume = {48},
  issn = {0899-8256},
  url = {http://www.sciencedirect.com/science/article/pii/S0899825603002458},
  doi = {10.1016/j.geb.2003.09.007},
  abstract = {Many centralized entry-level labor markets use the firm-proposing deferred-acceptance (DA) algorithm to compute the matching that is implemented among workers and firms. We propose a definition of the strategic options a worker faces in the DA-algorithm. Then we develop a theory to advise workers who distinguish between the firms from which they believe not to receive a proposal, the firms from which they might receive a proposal, and the firms from which they certainly receive a proposal. If a worker is not able to deduce which new proposals she receives after having rejected others, then it is not profitable for her to submit a list that reverses the true ranking of any two acceptable firms. Furthermore, it is not beneficial for her to include a firm in her submitted list that is unacceptable to her.},
  number = {2},
  urldate = {2015-01-27},
  journal = {Games and Economic Behavior},
  author = {Ehlers, Lars},
  month = aug,
  year = {2004},
  keywords = {General truncation strategies,Incomplete information},
  pages = {249--270},
  file = {Ehlers_2004_In search of advice for participants in matching markets which use the.pdf:/Users/martinvanderlinden/Box Sync/Literature/storage/454XJSN6/Ehlers_2004_In search of advice for participants in matching markets which use the.pdf:application/pdf;ScienceDirect Snapshot:/Users/martinvanderlinden/Box Sync/Literature/storage/N9MIDB3A/S0899825603002458.html:text/html}
}

@article{Hsu2011,
  title = {Prediction Market for Climate Outcomes, A},
  volume = {83},
  url = {http://heinonline.org/HOL/Page?handle=hein.journals/ucollr83\&id=181\&div=\&collection=journals},
  journal = {University of Colorado Law Review},
  author = {Hsu, Shi-Ling},
  year = {2011},
  pages = {179},
  file = {Law Journal Library - HeinOnline.org:/Users/martinvanderlinden/Box Sync/Literature/storage/TM5K4WM5/Page.html:text/html}
}

**Comment by AllThatIsTheCase** [comment] 2015-02-20 23:07
That is indeed odd, as that is the fallback reference in case nothing could be generated, but a) you have set an explicit citekey, and b) there is enough info to generate a sensible key even if you hadn't.

Do you have both Zotero FF and Zotero Standalone running simultaneously? There's a known problem of database locking that I don't know how to fix yet. If not, could you go into Preferences->Advanced, enable logging, export those two to Bib(La)TeX (whichever you used), and then send a report again?

**Comment by vanderlindenma** [comment] 2015-02-20 23:14
No, the two version are not being run simultaneously.

Here is the new log with enabled logging : http://goo.gl/JGRHjQ.

I'll have to leave in 15 minutes or so, so don't be surprised if I stop answering. Until then feel free to ask for more tests, I'll be happy to help.

**Comment by AllThatIsTheCase** [comment] 2015-02-20 23:21
There's less in the logs than I would have expected. If you go to Preferences->Advanced->View log, there should be heaps more. Can you past that in a gist, or dump it into https://dbinbox.com/allthatisthecase?

**Comment by AllThatIsTheCase** [comment] 2015-02-20 23:22
If you have to leave, no problem. I have time tomorrow morning, so I can pick up at your convenience. Unfortunately I can't reproduce the problem here just yet.

**Comment by vanderlindenma** [comment] 2015-02-20 23:25
Ok, if there is other things you want me to try, feel free to post them in the next hours or so, and I’ll try them tomorrow when I see my emails.
-------------------------------
Martin Van der Linden

**Comment by AllThatIsTheCase** [comment] 2015-02-20 23:34
Just the logs, generated with logging enabled, and after that an export. I really can't (yet) make heads nor tails of it, and I can't (yet) reproduce. If the logs don't tell me enough, I'll create an instrumented version with more verbose logging.

**Comment by AllThatIsTheCase** [comment] 2015-02-20 23:48
Would you happen to know what version OSX could run on a blue or bondi blue iMac, and whether Firefox is available for it? I might need to get me a Mac to troubleshoot such issues -- I've tried a hackintosh in a VM, but even if it does work occasionally, it's unbearably slow.

**Comment by AllThatIsTheCase** [comment] 2015-02-21 08:52
I've released 0.7.29 which has improved error logging. Could you please try again:

* go to Preverences->Advanced->Enable after restart
* fully close Firefox
* start Firefox
* export these two entries
* report ZotPlus errors from the gear menu (I don't need the references in this case)

**Comment by vanderlindenma** [comment] 2015-02-21 16:11
http://goo.gl/z3cec8
-------------------------------
Martin Van der Linden

**Comment by AllThatIsTheCase** [comment] 2015-02-21 16:41
Are you sure you followed the above steps? At minimum I would have expected to see `(3)(+0000000): Using data directory` in the log, but it's not there. It's very important that all Firefox windows are closed -- if one remains open, Firefox really doesn't do a full restart, and logging isn't enabled.

**Comment by vanderlindenma** [comment] 2015-02-21 17:24
Thought I did, but might have screwed up. Here is another try : http://goo.gl/dJkuPU <http://goo.gl/dJkuPU>.
-------------------------------
Martin Van der Linden

**Comment by AllThatIsTheCase** [comment] 2015-02-21 17:34
That got me the log, but there's nothing out of the ordinary in there. Can you install https://dl.dropboxusercontent.com/u/5300806/zotero-better-bibtex-0.7.30.xpi, restart (will be asked after install), preverences->advanced->enable (the button, not the checkbox), export those two again, and send the log? This version has more detailed logging. It's functionally equivalent otherwise.

**Comment by AllThatIsTheCase** [comment] 2015-02-21 17:38
BTW, there's a file named `betterbibtex.sqlite` in your profile directory; could you fully shut down Firefox (there should be no file with `journal` in the name in that directory after shutdown) and drop that file into https://dbinbox.com/allthatisthecase? I'm curious what the state of your citekey cache is.

**Comment by vanderlindenma** [comment] 2015-02-21 17:42
http://goo.gl/KcWBDm <http://goo.gl/KcWBDm>.

-------------------------------
Martin Van der Linden

**Comment by vanderlindenma** [comment] 2015-02-21 17:44
done (there was indeed no “journal” file in the directory after shut down).

-------------------------------
Martin Van der Linden

**Comment by AllThatIsTheCase** [comment] 2015-02-21 22:18
OK, the database explains everything. I have no idea how things could have gotten into this state, however, which I find a little worrisome. Fortunately, it's easily fixable.

Try installing https://dl.dropboxusercontent.com/u/5300806/zotero-better-bibtex-0.7.30.xpi (it's a new version, which I'll probably release tomorrow). There's a new option (well it's an old option, but the GUI is new) in the preferences, "re-scan keys on restart". Tick that, restart (fully!), and I suspect the problem should be gone. The checkmark will also be gone.

**Comment by AllThatIsTheCase** [comment] 2015-02-21 22:20
What I wouldn't give for the Zotero devs to finally deliver that custom field stuff they've been talking about for ages. If I could hae done all this in cleanly supported fields, this problem would have been impossible.

**Comment by vanderlindenma** [comment] 2015-02-21 22:24
Works like a charm, many thanks! I’ll close the issue. Good luck if you try to figure out the deeper cause of the issue. 
-------------------------------
Martin Van der Linden

**Comment by AllThatIsTheCase** [comment] 2015-02-21 22:26
Phew, that's good to hear. The best option really is to get the infrastructure fixed -- until then there's always going to be points where it's brittle.

**Closed** 2015-02-21 22:26 UTC
